mindmap
  root[Properties]
    TL[Intersections]
        Current Phase
        Green Time Duration
        Pressure
    LE[Lanes]
        Average Speed
        Occupancy
        Queue Length
    LE[Vehicles]
        Waiting Time
        Accumulated Waiting Time
